version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "telegram-otlojka-bot"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"